Criação das spec para CRUD de releases
ruby-joinville/get-on-rails pull request #6
Opened 2019-05-26 13:15 UTC by pedroCervi

Hello!

These are these specs for the releases CRUD. It is expected them to fails since we will be making these changes on the workshop. Soon I will share the tutorial with you guys so we can match tutorial and specs.

2019-05-27 16:36 UTC, cuzik requested changes
:alien:

2019-05-27 16:36 UTC, cuzik commented on spec/models/user_spec.rb
> +  it 'has many artists' do
Existe uma gem que faz o teste das relações 

https://github.com/thoughtbot/shoulda-matchers


o teste ficaria assim daí


```rb
context("Relationships") do
  it { should have_many(:artists) }
end
```

2019-05-27 16:36 UTC, cuzik commented on spec/models/release_spec.rb
> +  it 'belongs to artist' do
A mesma coisa aqui

ficaria 

```rb
context("Relationships") do
  it { should belong_to(:artist) }
end
```

2019-05-28 23:42 UTC, pedroCervi commented on spec/models/user_spec.rb
> +  it 'has many artists' do
como discutido vamos mostrar que existem essas facilidades no rails mas deixar aqui mais  manual, pra eles entenderem melhor o acesso a objetos relacionados

2019-05-28 23:44 UTC, cuzik approved these changes
:alien:

2019-05-28 23:44 UTC, merged